services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: sql_playground
    ports:
      - "5432:5432"
# docker compose up
# docker exec -it <container_name> psql -U user sql_playground
